---
# file: tasks/set-role-variables.yml
# set necessary role variables.
#

- name: set memcache_exporter_use_service = True, if not defined
  set_fact:
    memcache_exporter_use_service: True
  when: memcache_exporter_use_service is not defined
